accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("pick_username/", views.pick_username, name="pick-username"),
]

conversations/urls.py
from django.urls import path

from . import views

app_name = "conversations"
urlpatterns = [
    path("create_conversation/", views.create_conversation, name="create-conversation"),
    path("join_conversation/", views.join_conversation, name="join-conversation"),
    path("conversations/<id>/", views.view_conversation, name="view-conversation"),
    path("find_conversation/", views.find_conversation, name="find-conversation"),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
	path('', views.home_view, name='home'),
	path("login/", views.user_login, name="login"),
	path("logout/", views.logout_view, name="logout"),
	path("signup/", views.signup, name="signup"),
	path("profile/", views.profile, name="profile"),
	path('profile/delete/', views.delete_account, name='delete_account'),
	path("history/", views.history_view, name="history"),
	path("notifications/", views.notifications_view, name="notifications"),
]

templates/base.html
<!DOCTYPE html>
{% csrf_token %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>{{ title }}</title>
        <style>
            * {
            font-family: 'Karla', sans-serif;
            }
        </style>
        {% block head %}
        {% endblock head %}
    </head>
    <body class="container">
        <!-- Navbar -->
        <div class="my-3">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    <nav class="navbar navbar-expand navbar-dark bg-dark rounded">
                        <div class="container-fluid">
                            <a class="navbar-brand" href="#">
                                <img src="{% static 'images/rnd-logo.png' %}" alt="Logo" width="30" height="24">
                            </a>
                            <a class="navbar-brand" href="{% url 'core:home' %}">Qosyl</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                                <ul class="navbar-nav">
                                    {% if not user.is_authenticated %}
                                    <li class="nav-item">
                                      <a class="nav-link" href="{% url 'core:signup' %}">Sign Up</a>
                                    </li>
                                    {% else %}
                                    <li class="nav-item">
                                      <a class="nav-link" aria-current="page" href="{% url 'core:profile' %}">Profile</a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link" aria-current="page" href="{% url 'core:history' %}">History</a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link" aria-current="page" href="{% url 'core:notifications' %}">Notifications</a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
                                    </li>           
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Alert messages -->
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="messages">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Content -->
        <main>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                Join a conversation
            </div>
            <div class="card-body">
                <div class="mb-3">
                    <label for="conversationID" class="form-label">Conversation ID:</label>
                    <input type="text" class="form-control" id="conversationID" placeholder="b6559317-dd09-4ed0-9a06-3cb163f31db3">
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button type="button" class="btn btn-lg btn-success" id="join-conversation">Join conversation!</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                New conversation
            </div>
            <div class="card-body">
                <div id="create-conversation-div"></div>
                <div class="row gap-2 mt-8">
                    <button type="button" class="btn btn-lg btn-info" id="create-conversation">Create</button>
                    <button type="button" class="btn btn-lg btn-info" id="find-conversation">Find</button>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block scripts %}
<script>
    const csrftoken = document.querySelector("[name=csrfmiddlewaretoken]").value;

    const createConversationDiv = document.querySelector(
    "#create-conversation-div"
    );
    const createConversationBtn = document.querySelector("#create-conversation");
    const findConversationBtn = document.querySelector("#find-conversation");

    const conversationIdInputDiv = document.querySelector("#conversationID");
    const joinConversationBtn = document.querySelector("#join-conversation");

    const messagesDiv = document.querySelector(".messages");

    const fetchPostOptions = {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrftoken,
    },
    };

    const flashMessage = (message, status) => {
        return messagesDiv.insertAdjacentHTML(
        "beforeend",
        `
                                            <div class="alert alert-${status} alert-dismissible fade show" role="alert">
                                                    ${message}
                                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>`
    );
    };

    
    
    createConversationBtn.onclick = (e) => {
    e.preventDefault();

    e.target.disabled = true;
    e.target.innerHTML +=
        ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>';

    fetch("{% url 'conversations:create-conversation' %}", fetchPostOptions, )
        .then((response) => {
            if (!response.ok) {
                return Promise.reject(response);
            }
            return response.json();
        })
        .then((data) => {
            createConversationDiv.innerHTML = `
                    <div class="mb-3">
                        <label for="conversationID" class="form-label">Conversation ID:</label>
                        <input type="text" class="form-control" id="conversationID" value="${data.data.conversation_id}" disabled>
                    </div>`;
        })
        .catch((error) => {
            if (typeof error.json === "function") {
                error
                    .json()
                    .then((apiError) => {
                        flashMessage(apiError.message, "danger");
                    })
                    .catch((genericError) => {
                        flashMessage(genericError.statusText, "danger");
                    });
            } else {
                console.log(error);
            }
        });

    e.target.disabled = false;
    e.target.innerHTML = "Create conversation";
    };

    joinConversationBtn.onclick = (e) => {
    e.preventDefault();

    e.target.disabled = true;
    e.target.innerHTML +=
        ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>';

    const conversationIDInput = conversationIdInputDiv.value;

    if (!conversationIDInput) {
        conversationIdInputDiv.classList.add("is-invalid");
        flashMessage("Conversation ID field cannot be empty!", "danger");

        e.target.disabled = false;
        e.target.innerHTML = "Continue";

        return;
    }

    const body = JSON.stringify({ conversation_id: conversationIDInput });

    fetch("{% url 'conversations:join-conversation' %}", { ...fetchPostOptions, body })
        .then((response) => {
            if (!response.ok) {
                return Promise.reject(response);
            }
            return response.json();
        })
        .then((data) => {
            flashMessage(data.message, "success");

            setTimeout(() => {
                window.location.replace(
                    `${window.location.origin}/conversations/${data.data.conversation_id}/`
                );
            }, 500);
        })
        .catch((error) => {
            if (typeof error.json === "function") {
                error
                    .json()
                    .then((apiError) => {
                        flashMessage(apiError.message, "danger");
                    })
                    .catch((genericError) => {
                        flashMessage(genericError.statusText, "danger");
                    });
            } else {
                console.log(error);
            }

            conversationIdInputDiv.classList.add("is-invalid");
        });

    e.target.disabled = false;
    e.target.innerHTML = "Continue";
    conversationIdInputDiv.classList.remove("is-invalid");
    };


    findConversationBtn.onclick = (e) => {
    e.preventDefault();

    e.target.disabled = true;
    e.target.innerHTML +=
        ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>';

    fetch("{% url 'conversations:find-conversation' %}", fetchPostOptions, )
        .then((response) => {
            if (!response.ok) {
                return Promise.reject(response);
            }
            return response.json();
        })
        .then((data) => {
            flashMessage(data.message, "success");

            setTimeout(() => {
                window.location.replace(
                    `${window.location.origin}/conversations/${data.data.conversation_id}/`
                );
            }, 500);
        })
        .catch((error) => {
            if (typeof error.json === "function") {
                error
                    .json()
                    .then((apiError) => {
                        flashMessage(apiError.message, "danger");
                    })
                    .catch((genericError) => {
                        flashMessage(genericError.statusText, "danger");
                    });
            } else {
                console.log(error);
            }
        });

    e.target.disabled = false;
    e.target.innerHTML = "Create conversation";
    };

</script>
{% endblock scripts %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    {% if username %}
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                Join a conversation
            </div>
            <div class="card-body">
                <div class="mb-3">
                    <label for="conversationID" class="form-label">Conversation ID:</label>
                    <input type="text" class="form-control" id="conversationID" placeholder="b6559317-dd09-4ed0-9a06-3cb163f31db3">
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button type="button" class="btn btn-lg btn-success" id="join-conversation">Join conversation!</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                Create a conversation
            </div>
            <div class="card-body">
                <div id="create-conversation-div"></div>
                <div class="d-grid gap-2 mt-4">
                    <button type="button" class="btn btn-lg btn-info" id="create-conversation">Create conversation</button>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                Pick a username
            </div>
            <div class="card-body">
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" placeholder="johndoe">
                    <div id="usernameHelp" class="form-text">Alphanumeric, -, ., _ are allowed. Min 4 characters. Max 25 characters.</div>
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button type="button" class="btn btn-primary" id="pickUsernameBtn">Continue!</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}
{% block scripts %}
<script>
    const csrftoken = document.querySelector("[name=csrfmiddlewaretoken]").value;

    {% if username %}
    const createConversationDiv = document.querySelector(
    "#create-conversation-div"
    );
    const createConversationBtn = document.querySelector("#create-conversation");

    const conversationIdInputDiv = document.querySelector("#conversationID");
    const joinConversationBtn = document.querySelector("#join-conversation");
    {% else %}
    const usernameInputDiv = document.querySelector("#username");
    const pickUsernameBtn = document.querySelector("#pickUsernameBtn");
    {% endif %}

    const messagesDiv = document.querySelector(".messages");

    const fetchPostOptions = {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrftoken,
    },
    };

    const flashMessage = (message, status) => {
        return messagesDiv.insertAdjacentHTML(
        "beforeend",
        `
                                            <div class="alert alert-${status} alert-dismissible fade show" role="alert">
                                                    ${message}
                                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>`
    );
    };

    {% if not username %}
    pickUsernameBtn.onclick = (e) => {
    e.preventDefault();

    e.target.disabled = true;
    e.target.innerHTML +=
        ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>';

    const usernameInput = usernameInputDiv.value;

    if (!usernameInput) {
        usernameInputDiv.classList.add("is-invalid");
        flashMessage("Username field cannot be empty!", "danger");

        e.target.disabled = false;
        e.target.innerHTML = "Continue";

        return;
    }

    if (!/^([a-zA-Z0-9]|[-._](?![-._])){4,25}$/.test(usernameInput)) {
        usernameInputDiv.classList.add("is-invalid");
        flashMessage(
            "Username is invalid! Please choose a valid one.",
            "danger"
        );

        e.target.disabled = false;
        e.target.innerHTML = "Continue";

        return;
    }

    const body = JSON.stringify({ username: usernameInput });

    fetch("{% url 'accounts:pick-username' %}", { ...fetchPostOptions, body })
        .then((response) => {
            if (!response.ok) {
                return Promise.reject(response);
            }
            return response.json();
        })
        .then((data) => {
            flashMessage(data.message, "success");

            setTimeout(() => {
                window.location.reload(true);
            }, 1000);
        })
        .catch((error) => {
            if (typeof error.json === "function") {
                error
                    .json()
                    .then((apiError) => {
                        flashMessage(apiError.message, "danger");
                    })
                    .catch((genericError) => {
                        flashMessage(genericError.statusText, "danger");
                    });
            } else {
                console.log(error);
            }

            usernameInputDiv.classList.add("is-invalid");
        });

    e.target.disabled = false;
    e.target.innerHTML = "Continue";
    usernameInputDiv.classList.remove("is-invalid");
    };

    {% else %}
    createConversationBtn.onclick = (e) => {
    e.preventDefault();

    e.target.disabled = true;
    e.target.innerHTML +=
        ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>';

    fetch("{% url 'conversations:create-conversation' %}", fetchPostOptions)
        .then((response) => {
            if (!response.ok) {
                return Promise.reject(response);
            }
            return response.json();
        })
        .then((data) => {
            createConversationDiv.innerHTML = `
                    <div class="mb-3">
                        <label for="conversationID" class="form-label">Conversation ID:</label>
                        <input type="text" class="form-control" id="conversationID" value="${data.data.conversation_id}" disabled>
                    </div>`;
        })
        .catch((error) => {
            if (typeof error.json === "function") {
                error
                    .json()
                    .then((apiError) => {
                        flashMessage(apiError.message, "danger");
                    })
                    .catch((genericError) => {
                        flashMessage(genericError.statusText, "danger");
                    });
            } else {
                console.log(error);
            }
        });

    e.target.disabled = false;
    e.target.innerHTML = "Create conversation";
    };

    joinConversationBtn.onclick = (e) => {
    e.preventDefault();

    e.target.disabled = true;
    e.target.innerHTML +=
        ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>';

    const conversationIDInput = conversationIdInputDiv.value;

    if (!conversationIDInput) {
        conversationIdInputDiv.classList.add("is-invalid");
        flashMessage("Conversation ID field cannot be empty!", "danger");

        e.target.disabled = false;
        e.target.innerHTML = "Continue";

        return;
    }

    const body = JSON.stringify({ conversation_id: conversationIDInput });

    fetch("{% url 'conversations:join-conversation' %}", { ...fetchPostOptions, body })
        .then((response) => {
            if (!response.ok) {
                return Promise.reject(response);
            }
            return response.json();
        })
        .then((data) => {
            flashMessage(data.message, "success");

            setTimeout(() => {
                window.location.replace(
                    `${window.location.origin}/conversations/${data.data.conversation_id}/`
                );
            }, 500);
        })
        .catch((error) => {
            if (typeof error.json === "function") {
                error
                    .json()
                    .then((apiError) => {
                        flashMessage(apiError.message, "danger");
                    })
                    .catch((genericError) => {
                        flashMessage(genericError.statusText, "danger");
                    });
            } else {
                console.log(error);
            }

            conversationIdInputDiv.classList.add("is-invalid");
        });

    e.target.disabled = false;
    e.target.innerHTML = "Continue";
    conversationIdInputDiv.classList.remove("is-invalid");
    };
    {% endif %}

</script>
{% endblock scripts %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                Log In
            </div>
            <form method='POST', action="{% url 'core:login' %}">
                {% csrf_token %}
                <div class="card-body">
                    <div class="mb-3">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" class="form-control" id="username" placeholder="johndoe" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password:</label>
                        <input type="password" class="form-control" id="password" placeholder="********" name="password">
                    </div>
                    <div class="d-grid gap-2 mt-4">
                        <button type="submit" class="btn btn-primary" id="pickUsernameBtn">Continue!</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8 my-3">

        <div class="container-xl px-4 mt-4">
            <div class="row">
                <div class="col-xl-16">
                    <!-- Account details card-->
                    <form method="post">
                        {% csrf_token %}
                        <div class="card mb-4">
                            <div class="card-header">Account Details</div>
                            <div class="card-body">
                                <form>
                                    <!-- Form Group (username)-->
                                    <div class="mb-3">
                                        <label class="small mb-1" for="inputUsername">Username (how your name will appear to other users on the site)</label>
                                        <input class="form-control" id="inputUsername" type="text" placeholder="Enter your username" name="username" value="{{ user.username }}" readonly>
                                    </div>
                                    <!-- Form Row-->
                                    <div class="row gx-3 mb-3">
                                        <!-- Form Group (first name)-->
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputFirstName">First name</label>
                                            <input class="form-control" id="inputFirstName" type="text" placeholder="Enter your first name" name="first_name" value="{{ user.first_name }}">
                                        </div>
                                        <!-- Form Group (last name)-->
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputLastName">Last name</label>
                                            <input class="form-control" id="inputLastName" type="text" placeholder="Enter your last name" name="last_name" value="{{ user.last_name }}">
                                        </div>
                                    </div>
                                    <!-- Form Group (email address)-->
                                    <div class="mb-3">
                                        <label class="small mb-1" for="inputEmailAddress">Email address</label>
                                        <input class="form-control" id="inputEmailAddress" type="email" placeholder="Enter your email address" name="email" value="{{ user.email }}">
                                    </div>
                                    <!-- Save changes button-->
                                    <button class="btn btn-primary" type="submit" name="update_profile">Save changes</button>
                                </form>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <div class="container-xl px-4 mt-4">
            <div class="row">
                <div class="col-lg-16">
                    <!-- Change password card-->
                    <div class="card mb-4">
                        <div class="card-header">Change Password</div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <!-- Form Group (current password)-->
                                <div class="mb-3">
                                    <label class="small mb-1" for="currentPassword">Current Password</label>
                                    <input class="form-control" id="currentPassword" type="password" placeholder="Enter current password" name="current_password">
                                </div>
                                <!-- Form Group (new password)-->
                                <div class="mb-3">
                                    <label class="small mb-1" for="newPassword">New Password</label>
                                    <input class="form-control" id="newPassword" type="password" placeholder="Enter new password" name="new_password">
                                </div>
                                <!-- Form Group (confirm password)-->
                                <div class="mb-3">
                                    <label class="small mb-1" for="confirmPassword">Confirm Password</label>
                                    <input class="form-control" id="confirmPassword" type="password" placeholder="Confirm new password" name="repeat_new_password">
                                </div>
                                <button class="btn btn-primary" type="submit" name="change_password">Save</button>
                            </form>
                        </div>
                    </div>
                    
                    <!-- Delete account card-->
                    <div class="card mb-4">
                        <form method="post" action="{% url 'core:delete_account' %}">
                            {% csrf_token %}
                            <div class="card-header">Delete Account</div>
                            <div class="card-body">
                                <p>Deleting your account is a permanent action and cannot be undone. If you are sure you want to delete your account, select the button below.</p>
                                <button class="btn btn-danger-soft text-danger" type="submit" onclick="return confirm('Are you sure you want to delete your account?')">I understand, delete my account</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8 my-3">
        <div class="card">
            <div class="card-header text-center lead fw-bold">
                Registration
            </div>
            <form method='POST', action="{% url 'core:signup' %}">
                {% csrf_token %}
                <div class="card-body">
                    <div class="mb-3">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" class="form-control" id="username" placeholder="johndoe" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="password1" class="form-label">Password:</label>
                        <input type="password" class="form-control" id="password1" placeholder="********" name="password1">
                    </div>
                    <div class="mb-3">
                        <label for="password2" class="form-label">Repeat Password:</label>
                        <input type="password" class="form-control" id="password2" placeholder="********" name="password2">
                    </div>
                    <div class="d-grid gap-2 mt-4">
                        <button type="submit" class="btn btn-primary" id="pickUsernameBtn">Sign Up</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}